id: P20E3617D
initial_creation_type: input
source_metadata:
  title: Averting Obstacles
  language: pt
  description: 'A series of apotropaic practices and rites for averting obstacles
    and dispelling negativity:'
  volume:
    63398e0007d14024a350b4aeed003faf:
      title: The Ultimate, Natural Dispeller of Obstacles
      parent: General
    07ccb705488041bea6e78538585d14af:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Heart Sūtra
    dca10c8384d34a73a4d001eb759545dc:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Other
    90c862142f3d46bfbd9f8f3cc4873ad0:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      parent: Other
    a03d81af2f074ddaad7d5dfa8d7f64a9:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Repelling Invasion
    e3ce4d824d2f4cb39bc6a1eb865706cc:
      title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
      parent: Repelling Invasion
    20b6310940344f57824ab63cc1be2847:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    b9c46044741f48288d2d373be79d2e2a:
      title: Averting Obstacles through Sitātapatrā
      parent: Sitātapatrā
    1dc57c99de174c67be448d0f277aea66:
      title: A Short Practice for Averting Obstacles through Vajrakīla
      parent: Vajrakīla
created_at: '2022-03-01T02:55:09.615775'
last_modified_at: '2022-03-01T02:55:09.615778'
